name: Build extensions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to build against'
        required: true

env:
  JAVA_VERSION: 17

jobs:
  build-extension:
    name: Build extension
    strategy:
      matrix:
        repo:
          - Cuyler36/Ghidra-GameCube-Loader
          - Adubbz/Ghidra-Switch-Loader
          - Maschell/GhidraRPXLoader

    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download release
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ inputs.tag }}
          fileName: ghidra_*.zip
          extract: true

      - name: Setup environment
        run: |
          echo "GHIDRA_INSTALL_DIR=$(realpath ghidra_*/)" >> $GITHUB_ENV
          echo "REPO_NAME=$(basename "${{ matrix.repo }}")" >> $GITHUB_ENV

      - name: Checkout extension
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: ${{ env.REPO_NAME }}

      - name: Build extension
        working-directory: ${{ env.REPO_NAME }}
        run: |
          chmod +x gradlew
          ./gradlew

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}
          path: ${{ env.REPO_NAME }}/dist/*.zip

      - name: Add artifact to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: ${{ env.REPO_NAME }}/dist/*.zip
