name: Build extensions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to build against'
        required: true

env:
  JAVA_VERSION: 21

jobs:
  build-extension:
    name: Build extension
    strategy:
      matrix:
        include:
          - repo: Cuyler36/Ghidra-GameCube-Loader
            ref: rootcubed
          - repo: Adubbz/Ghidra-Switch-Loader
            ref: master
          - repo: Maschell/GhidraRPXLoader
            ref: main
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ inputs.tag }}
          fileName: ghidra_*.zip
          extract: true

      - name: Setup environment
        run: |
          echo "GHIDRA_INSTALL_DIR=$(realpath ghidra_*/)" >> $GITHUB_ENV
          echo "REPO_NAME=$(basename "${{ matrix.repo }}")" >> $GITHUB_ENV

      - name: Checkout extension
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          path: ${{ env.REPO_NAME }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: ${{ env.REPO_NAME }}
          gradle-version: "8.10"

      - name: Build extension
        working-directory: ${{ env.REPO_NAME }}
        run: gradle build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}-${{ inputs.tag }}
          path: ${{ env.REPO_NAME }}/dist/*.zip

      - name: Add artifact to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          files: ${{ env.REPO_NAME }}/dist/*.zip
